before:
  hooks:
    - go get -v -d
    - go mod tidy
    - go mod vendor
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=1
  goos:
    - linux
  goarch:
    - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archives:
  -
    files:
    - config.example.json
dockers:
 - ids:
    - go-via
   image_templates:
    - "docker.io/tribock/go-via:latest"
   build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
release:
  prerelease: auto
  draft: true