apiVersion: v1
kind: Namespace
metadata:
  name: souldeploy
  labels:
    pod-security.kubernetes.io/audit: privileged 
    pod-security.kubernetes.io/warn: privileged 
    pod-security.kubernetes.io/enforce: privileged  